// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_currency/test/CurrencyViewModel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_currency/Currency/Model/CurrencyModel.dart' as _i2;
import 'package:flutter_currency/Currency/Service/CurrencyService.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CurrencyModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyModel extends _i1.Mock implements _i2.CurrencyModel {
  MockCurrencyModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set data(List<_i2.CurrencyModelData>? _data) => super.noSuchMethod(
        Invocation.setter(
          #data,
          _data,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set httpStatus(int? _httpStatus) => super.noSuchMethod(
        Invocation.setter(
          #httpStatus,
          _httpStatus,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String getMockData() => (super.noSuchMethod(
        Invocation.method(
          #getMockData,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getMockData,
            [],
          ),
        ),
      ) as String);
}

/// A class which mocks [CurrencyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyService extends _i1.Mock implements _i4.CurrencyService {
  MockCurrencyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.CurrencyModel?> getCurrencyPairs() => (super.noSuchMethod(
        Invocation.method(
          #getCurrencyPairs,
          [],
        ),
        returnValue: _i5.Future<_i2.CurrencyModel?>.value(),
      ) as _i5.Future<_i2.CurrencyModel?>);
}
