name: flutter test

on:
  pull_request:
    branches: [ develop ]
    
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-version: [3.24.3]  # 指定 Flutter 版本，可以根據需求調整

    steps:
      # 檢出程式碼
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      # 設置 Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}

      # 顯示 Flutter 版本
      - name: Flutter version
        run: flutter --version

      # 安裝相依套件
      - name: Install dependencies
        run: flutter pub get

      # 運行測試
      - name: Run tests
        run: flutter test

      # 設置Java Version為17
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      # 打包Andorid APK 並拆分平台編譯
      - name: Check Build Andorid APK
        run: flutter build apk --split-per-abi

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
            artifacts: "build/app/outputs/flutter-apk/*.apk"
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: v1.0.${{ github.run_number }}
            generateReleaseNotes: true # 自動生成 Release Notes
            replacesArtifacts: true # 覆蓋舊的 Artifacts（如果有相同標籤）
#      # 打包iOS
#      - name: Check Build iOS
#        run:
#          flutter build ios
#          xcodebuild -workspace ios/Runner.xcworkspace \
#          -scheme Runner \
#          -configuration Release \
#          CODE_SIGNING_ALLOWED=NO

      # 可選：上傳測試覆蓋率報告
      # - name: Upload coverage to Coveralls
      #   uses: coverallsapp/github-action@v3
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
